package com.live.emmazone.utils

object AppConstants {
    var SEND_CHAT_PUSH = true
    const val SHARED_NAME = "emmaZone"
    const val AUTHORIZATION = "Authorization"
    const val SECURITY_KEY = "emmazone12@"
    const val SUCCESS_CODE = 200
    const val DEVICE_TYPE = "1"    //1 ->Android, 2->iOS
    const val USER_ROLE = "1"
    const val SELLER_ROLE = "3"
    const val GUEST = "guest"
    const val YEAR_FORMAT = "yyyy"
    const val TIME_FORMAT = "hh:mm a"
    const val DATE_FORMAT = "dd-MMM-yyyy, hh:mm a"


    const val PROFILE_TYPE = "profileType"
    const val USER_CHOICE = "userChoice"

    const val OPEN_BY_CART = "openByCart"
    const val USER_ID = "userId"
    const val USER2_ID = "user2Id"
    const val USER2_NAME = "user2Name"
    const val USER2_IMAGE = "user2Image"
    const val SHOP_NAME_VISIBLE = "shopNameVisible"
    const val USER = "user"
    const val SELLER = "seller"
    const val NAME = "name"
    const val IS_LOGIN = "isLogin"
    const val ROLE = "role"  //1-> User, 3-> Seller
    const val NOTIFICATION_TYPE = "notification_type"  //1-> On, 0-> Off
    const val SHOP_LISTING_RESPONSE = "shopListingResponse"
    const val Address_LIST_RESPONSE = "addressListResponse"
    const val WISH_LIST_RESPONSE = "wishListResponse"
    const val SHOP_DETAIL_RESPONSE = "shopDetailResponse"
    const val SHOP_ID = "shopId"
    const val IMAGES_ARRAYLIST = "imagesList"
    const val ORDER_ID = "orderId"
    const val NOTIFICATION_RESPONSE = "notificationResponse"
    const val SAVED_ADDRESS_RESPONSE = "saveAddress"
    const val PAYMENT_TYPE = "paymentType"
    const val SAVED_CARD_ID = "saveCardId"
    const val SAVED_CVV = "saveCvv"
    const val DISTANCE = "distance"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val LOCATION = "location"
    const val FILTER = "filter"
    const val SELECTED_BANK_ACCOUNT = "selectedBankAcc"


    /*******URLs*****/
//    const val BASE_URL = "http://192.168.1.153:8188/api/" //LOCAL URLs
    const val BASE_URL = "http://202.164.42.227:8188/api/"
    const val IMAGE_CATEGORY_URL = "http://202.164.42.227:8188/uploads/category/"
    const val IMAGE_USER_URL = "http://202.164.42.227:8188/uploads/user/"
    const val SHOP_IMAGE_URL = "http://202.164.42.8188/uploads/shop_images/"
    const val PRODUCT_IMAGE_URL = "http://202.164.42.227:8188/uploads/product/"
    const val SOCKET_BASE_URL = "http://202.164.42.227:8188/"
    const val SIGN_UP = "signup_user"
    const val OTP_VERIFY = "otp_verify"
    const val RESEND_OTP = "resend_otp"
    const val LOGIN = "login"
    const val TERMS = "terms"
    const val PRIVACY_POLICY = "privacy_policy"
    const val FORGOT_PASSWORD = "forgot_password"
    const val CATEGORY_LIST = "category_list"
    const val SELLER_SHOP_DETAILS = "seller_shop_details"
    const val DELETE_PRODUCT = "delete_product"
    const val ADD_SHOP = "add_shop"
    const val CHANGE_PASSWORD = "change_password"
    const val NOTIFICATION_LIST = "notification_list"
    const val NOTIFICATION_STATUS = "notification_status"
    const val PROFILE = "profile"
    const val EDIT_PROFILE = "edit_profile"
    const val ADD_NEW_ADDRESS = "add_new_address"
    const val ADDRESS_LIST = "address_list"
    const val SHOP_LIST = "shop_list"
    const val FAV_SHOP = "fav_shop"
    const val DELETE_ADDRESS = "delete_address"
    const val ADD_SHOP_PRODUCT = "add_shop_product"
    const val GET_SELECTED_CATEGORY = "get_selected_category"
    const val LOGOUT = "logout"
    const val RATING = "ratings"
    const val CATEGORY_COLOR_SIZE = "category_color_size"
    const val ADD_CARD = "addCard"
    const val CARD_LIST = "card_list"
    const val ADD_ACCOUNT = "add_account"
    const val WISH_LIST = "wish_list"
    const val SHOP_DETAIL = "shop_details"
    const val FAQ = "faq"
    const val EDIT_SHOP_PRODUCT = "edit_shop_product"
    const val PRODUCT_DETAIl = "product_detail"
    const val ADD_CART_ITEMS = "addCartItem"
    const val CART_LISTING = "cartItemsListing"
    const val DELETE_CART_ITEM = "deleteCartItem"
    const val EDIT_SHOP_DETAIL = "edit_shop_details"
    const val SALES = "sales"
    const val UPDATE_CART_ITEM = "updateCartItem"
    const val ADD_ORDER = "addOrder"
    const val ORDER_LISTING = "user_sales"
    const val ORDER_STATUS = "orderStatus"
    const val NOTIFICATION_READ = "isRead"
    const val GET_BANK_ACCOUNT = "get_bank_account"
    const val DELETE_BANK = "delete_bank"
    const val DELETE_CARD = "deleteCard"
    const val CANCEL_ORDER = "cancelOrder"
    const val MY_EARNING = "myEarnings"
    const val TRANSACTION_LIST = "transaction_list"
    const val WITHDRAW_REQUEST = "withdrawl"
    const val SEARCH_PRODUCT = "searchProduct"

}